use anyhow::{Context, Result, anyhow, bail};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::cli::{HooksArgs, HooksCommands, HooksRepoArgs};
use crate::path_utils::detect_repo_root;
use crate::sync::resolved_sync_config;
use crate::sync_schedule::{ScheduleBackend, current_backend, install_or_update_schedule};

const PACEFLOW_HOOK_MARKER: &str = "PACEFLOW_MANAGED_PRE_COMMIT_HOOK";
/// Sentinel written by the current composite hook. Its presence (in addition to
/// `PACEFLOW_HOOK_MARKER`) distinguishes a composite hook from the legacy `exec` shim.
const PACEFLOW_HOOK_KIND_COMPOSITE: &str = "paceflow-hook-kind: composite";
/// Filename (sibling of `pre-commit`) where a displaced foreign hook is backed up so the
/// composite hook can still run it.
const CHAINED_HOOK_FILENAME: &str = "pre-commit.paceflow-chained";
const PRECOMMIT_CONFIG_FILENAME: &str = ".pre-commit-config.yaml";
/// Substring the pre-commit.com framework writes into every hook it generates.
const PRECOMMIT_FRAMEWORK_MARKER: &str = "generated by pre-commit";
/// Filename pre-commit.com moves a displaced hook to during its migration flow.
const PRECOMMIT_LEGACY_FILENAME: &str = "pre-commit.legacy";

pub fn run(args: HooksArgs) -> Result<()> {
    match args.command {
        HooksCommands::Install(args) => install_hook(args.repo.as_deref(), args.force),
        HooksCommands::Uninstall(args) => uninstall_hook(args.repo.as_deref()),
        HooksCommands::Status(args) => status_hook(args.repo.as_deref()),
        HooksCommands::PreCommit(args) => run_pre_commit(args),
    }
}

fn run_pre_commit(args: HooksRepoArgs) -> Result<()> {
    let mut backend = current_backend();
    run_pre_commit_with_backend(args, backend.as_mut())
}

fn run_pre_commit_with_backend(
    args: HooksRepoArgs,
    backend: &mut dyn ScheduleBackend,
) -> Result<()> {
    let _repo_root = resolve_repo_root(args.repo.as_deref())?;
    check_sync_configured()?;
    ensure_schedule_installed(backend)
}

fn install_hook(repo: Option<&str>, force: bool) -> Result<()> {
    let repo_root = resolve_repo_root(repo)?;
    let hook_path = pre_commit_hook_path(&repo_root)?;
    let existing = read_existing_hook(&hook_path)?;
    let kind = classify_hook(existing.as_deref());

    let legacy_path = legacy_hook_path(&hook_path);
    let legacy_is_paceflow = read_existing_hook(&legacy_path)?
        .as_deref()
        .is_some_and(is_paceflow_managed);

    if let Some(parent) = hook_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create hook directory {}", parent.display()))?;
    }

    // Repair the Windows-migrated state first: pre-commit moved our hook to `pre-commit.legacy`
    // and installed its own wrapper at `pre-commit`. Re-take ownership with the composite (its
    // `pre-commit run` fallback reproduces the framework invocation) and drop the stale legacy hook.
    if kind == HookKind::PrecommitFramework && legacy_is_paceflow {
        write_composite_hook(&hook_path)?;
        fs::remove_file(&legacy_path)
            .with_context(|| format!("failed to remove {}", legacy_path.display()))?;
        println!(
            "Repaired pre-commit migration: reinstalled the Paceflow composite hook at {} and removed {}.",
            hook_path.display(),
            legacy_path.display()
        );
        report_precommit_coverage(&repo_root, &hook_path);
        return Ok(());
    }

    match kind {
        HookKind::None => {
            write_composite_hook(&hook_path)?;
            println!(
                "Installed Paceflow composite pre-commit hook at {}",
                hook_path.display()
            );
        }
        HookKind::PaceflowComposite | HookKind::PaceflowPlain => {
            write_composite_hook(&hook_path)?;
            println!(
                "Updated Paceflow composite pre-commit hook at {}",
                hook_path.display()
            );
        }
        HookKind::PrecommitFramework | HookKind::OtherForeign => {
            let existing = existing.expect("foreign hook classification implies contents");
            if force {
                write_composite_hook(&hook_path)?;
                println!(
                    "Overwrote existing pre-commit hook at {} with the Paceflow composite hook (--force).",
                    hook_path.display()
                );
            } else {
                let chained_path = chained_hook_path(&hook_path);
                if chained_path.exists() {
                    bail!(
                        "a chained hook backup already exists at {} but the active hook is not Paceflow-managed.\n\
Resolve this manually (restore or remove the backup), or re-run with --force to overwrite.",
                        chained_path.display()
                    );
                }
                fs::write(&chained_path, existing.as_bytes())
                    .with_context(|| format!("failed to write {}", chained_path.display()))?;
                set_executable(&chained_path)?;
                write_composite_hook(&hook_path)?;
                println!(
                    "Chained existing pre-commit hook: backed it up to {} and installed the Paceflow composite hook at {}.\n\
The composite runs the Paceflow gate, then your original hook. Run `paceflow hooks uninstall` to restore it.",
                    chained_path.display(),
                    hook_path.display()
                );
            }
        }
    }

    report_precommit_coverage(&repo_root, &hook_path);
    Ok(())
}

/// Write the composite hook to `hook_path` and mark it executable.
fn write_composite_hook(hook_path: &Path) -> Result<()> {
    fs::write(hook_path, hook_contents())
        .with_context(|| format!("failed to write {}", hook_path.display()))?;
    set_executable(hook_path)
}

/// After install, tell the user whether a `.pre-commit-config.yaml` will actually run.
fn report_precommit_coverage(repo_root: &Path, hook_path: &Path) {
    if !precommit_config_path(repo_root).exists() {
        return;
    }
    let has_chained = chained_hook_path(hook_path).exists();
    if has_chained || precommit_on_path() {
        println!(
            "Detected {PRECOMMIT_CONFIG_FILENAME}: the composite hook will also run your pre-commit checks."
        );
    } else {
        println!(
            "Warning: {PRECOMMIT_CONFIG_FILENAME} is present but `pre-commit` is not on PATH, so its lint/format checks will NOT run locally (CI may still fail).\n\
Install it (e.g. `pipx install pre-commit`) so the composite hook can invoke your checks."
        );
    }
}

fn uninstall_hook(repo: Option<&str>) -> Result<()> {
    let repo_root = resolve_repo_root(repo)?;
    let hook_path = pre_commit_hook_path(&repo_root)?;

    let Some(existing) = read_existing_hook(&hook_path)? else {
        println!("No pre-commit hook found at {}", hook_path.display());
        return Ok(());
    };

    if !is_paceflow_managed(&existing) {
        bail!(
            "refusing to remove existing non-Paceflow pre-commit hook at {}",
            hook_path.display()
        );
    }

    // If we displaced a foreign hook when installing, restore it instead of just deleting.
    let chained_path = chained_hook_path(&hook_path);
    if chained_path.exists() {
        restore_hook(&chained_path, &hook_path)?;
        set_executable(&hook_path)?;
        println!(
            "Removed the Paceflow composite hook and restored the previously chained pre-commit hook at {}.",
            hook_path.display()
        );
        return Ok(());
    }

    fs::remove_file(&hook_path)
        .with_context(|| format!("failed to remove {}", hook_path.display()))?;
    println!(
        "Removed Paceflow pre-commit setup gate from {}",
        hook_path.display()
    );
    Ok(())
}

/// Move `from` onto `to`, falling back to copy+remove when `rename` fails (e.g. across devices).
fn restore_hook(from: &Path, to: &Path) -> Result<()> {
    match fs::rename(from, to) {
        Ok(()) => Ok(()),
        Err(_) => {
            fs::copy(from, to).with_context(|| {
                format!("failed to restore {} to {}", from.display(), to.display())
            })?;
            fs::remove_file(from)
                .with_context(|| format!("failed to remove {}", from.display()))?;
            Ok(())
        }
    }
}

fn status_hook(repo: Option<&str>) -> Result<()> {
    let repo_root = resolve_repo_root(repo)?;
    let hook_path = pre_commit_hook_path(&repo_root)?;

    let existing = read_existing_hook(&hook_path)?;
    let kind = classify_hook(existing.as_deref());
    let has_chained = chained_hook_path(&hook_path).exists();
    let config_present = precommit_config_path(&repo_root).exists();

    match kind {
        HookKind::None => {
            println!(
                "Paceflow pre-commit hook is not installed at {}",
                hook_path.display()
            );
        }
        HookKind::PaceflowComposite => {
            println!(
                "Paceflow composite pre-commit hook is installed at {}",
                hook_path.display()
            );
            if has_chained {
                println!(
                    "  It also runs a chained hook at {}.",
                    chained_hook_path(&hook_path).display()
                );
            }
        }
        HookKind::PaceflowPlain => {
            println!(
                "A legacy Paceflow pre-commit shim is installed at {} (it does not run the repo's own checks).",
                hook_path.display()
            );
            println!("  Run `paceflow hooks install` to upgrade it to the composite hook.");
        }
        HookKind::PrecommitFramework => {
            println!(
                "A pre-commit framework hook (not Paceflow) is installed at {}.",
                hook_path.display()
            );
        }
        HookKind::OtherForeign => {
            println!(
                "A non-Paceflow pre-commit hook exists at {}.",
                hook_path.display()
            );
        }
    }

    // Windows-migration diagnosis: pre-commit moved our hook to `pre-commit.legacy`.
    let legacy_path = legacy_hook_path(&hook_path);
    let legacy_is_paceflow = read_existing_hook(&legacy_path)?
        .as_deref()
        .is_some_and(is_paceflow_managed);
    if kind == HookKind::PrecommitFramework && legacy_is_paceflow {
        println!(
            "  Detected pre-commit migration: the Paceflow hook was moved to {}. On Windows this breaks commits (the `#!/bin/sh` legacy hook can't be executed).",
            legacy_path.display()
        );
        println!(
            "  Run `paceflow hooks install` to repair (Paceflow re-takes ownership and invokes pre-commit itself)."
        );
    }

    if config_present {
        let will_run = match kind {
            HookKind::PaceflowComposite => has_chained || precommit_on_path(),
            HookKind::PrecommitFramework | HookKind::OtherForeign => true,
            _ => false,
        };
        if will_run {
            println!("  {PRECOMMIT_CONFIG_FILENAME} is present and will be invoked on commit.");
        } else if kind == HookKind::PaceflowComposite {
            println!(
                "  Warning: {PRECOMMIT_CONFIG_FILENAME} is present but `pre-commit` is not on PATH, so its checks will NOT run locally. Install it (e.g. `pipx install pre-commit`)."
            );
        } else if kind == HookKind::PaceflowPlain {
            println!(
                "  Warning: {PRECOMMIT_CONFIG_FILENAME} is present but the legacy shim never invokes it, so lint/format checks are silently skipped locally. Run `paceflow hooks install` to fix."
            );
        }
    }
    Ok(())
}

fn check_sync_configured() -> Result<()> {
    match resolved_sync_config() {
        Ok(Some(_)) => Ok(()),
        Ok(None) => {
            bail!("paceflow sync is not configured for this machine.\nRun: paceflow sync config")
        }
        Err(err) => bail!("invalid paceflow sync configuration: {err}"),
    }
}

fn ensure_schedule_installed(backend: &mut dyn ScheduleBackend) -> Result<()> {
    install_or_update_schedule(backend).map(|_| ()).map_err(|err| {
        anyhow!(
            "paceflow periodic sync schedule is not installed and could not be configured: {err}\nRun: paceflow sync schedule install"
        )
    })
}

fn resolve_repo_root(repo: Option<&str>) -> Result<PathBuf> {
    let candidate = match repo {
        Some(repo) => PathBuf::from(repo),
        None => std::env::current_dir()?,
    };
    let absolute = if candidate.is_absolute() {
        candidate
    } else {
        std::env::current_dir()?.join(candidate)
    };
    detect_repo_root(&absolute).ok_or_else(|| {
        anyhow!(
            "could not determine a git repository root from {}",
            absolute.display()
        )
    })
}

fn pre_commit_hook_path(repo_root: &Path) -> Result<PathBuf> {
    let output = Command::new("git")
        .current_dir(repo_root)
        .args(["rev-parse", "--git-path", "hooks/pre-commit"])
        .output()
        .context("failed to locate git hooks directory")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("failed to locate git hooks directory: {}", stderr.trim());
    }
    let raw = String::from_utf8(output.stdout)?.trim().to_string();
    if raw.is_empty() {
        bail!("git returned an empty pre-commit hook path");
    }
    let path = PathBuf::from(raw);
    if path.is_absolute() {
        Ok(path)
    } else {
        Ok(repo_root.join(path))
    }
}

fn read_existing_hook(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(contents) => Ok(Some(contents)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(err).with_context(|| format!("failed to read {}", path.display())),
    }
}

/// What is currently installed at the `pre-commit` hook path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HookKind {
    /// No hook file exists.
    None,
    /// The current composite hook (runs the gate, then chains the repo's checks).
    PaceflowComposite,
    /// A legacy Paceflow shim (`exec paceflow hooks pre-commit`) — still carries the marker.
    PaceflowPlain,
    /// A hook generated by the pre-commit.com framework.
    PrecommitFramework,
    /// Any other hook we did not write.
    OtherForeign,
}

fn classify_hook(contents: Option<&str>) -> HookKind {
    match contents {
        None => HookKind::None,
        Some(contents) if contents.contains(PACEFLOW_HOOK_MARKER) => {
            if contents.contains(PACEFLOW_HOOK_KIND_COMPOSITE) {
                HookKind::PaceflowComposite
            } else {
                HookKind::PaceflowPlain
            }
        }
        Some(contents) if contents.contains(PRECOMMIT_FRAMEWORK_MARKER) => {
            HookKind::PrecommitFramework
        }
        Some(_) => HookKind::OtherForeign,
    }
}

fn is_paceflow_managed(contents: &str) -> bool {
    matches!(
        classify_hook(Some(contents)),
        HookKind::PaceflowComposite | HookKind::PaceflowPlain
    )
}

/// Sibling path where a displaced foreign hook is backed up.
fn chained_hook_path(hook_path: &Path) -> PathBuf {
    hook_path.with_file_name(CHAINED_HOOK_FILENAME)
}

/// Sibling path pre-commit.com uses when it migrates an existing hook aside.
fn legacy_hook_path(hook_path: &Path) -> PathBuf {
    hook_path.with_file_name(PRECOMMIT_LEGACY_FILENAME)
}

fn precommit_config_path(repo_root: &Path) -> PathBuf {
    repo_root.join(PRECOMMIT_CONFIG_FILENAME)
}

/// Whether the `pre-commit` framework CLI is available on PATH.
fn precommit_on_path() -> bool {
    Command::new("pre-commit")
        .arg("--version")
        .output()
        .map(|out| out.status.success())
        .unwrap_or(false)
}

fn hook_contents() -> String {
    format!(
        "#!/bin/sh\n\
# {marker}\n\
# {kind}\n\
root=\"$(git rev-parse --show-toplevel 2>/dev/null)\" || exit 1\n\
hook_dir=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"\n\
\n\
if ! command -v paceflow >/dev/null 2>&1; then\n\
  echo \"paceflow is required for this repo. Install it, then run: paceflow sync config\" >&2\n\
  exit 1\n\
fi\n\
\n\
# 1) Paceflow setup gate (sync config + periodic schedule). Blocks the commit on failure.\n\
paceflow hooks pre-commit --repo \"$root\" || exit $?\n\
\n\
# 2) Run the repository's own pre-commit checks so they are not skipped.\n\
chained=\"$hook_dir/{chained}\"\n\
if [ -x \"$chained\" ]; then\n\
  \"$chained\" \"$@\" || exit $?\n\
elif [ -f \"$root/{config}\" ] && command -v pre-commit >/dev/null 2>&1; then\n\
  ( cd \"$root\" && pre-commit run --hook-stage pre-commit ) || exit $?\n\
fi\n\
\n\
exit 0\n",
        marker = PACEFLOW_HOOK_MARKER,
        kind = PACEFLOW_HOOK_KIND_COMPOSITE,
        chained = CHAINED_HOOK_FILENAME,
        config = PRECOMMIT_CONFIG_FILENAME,
    )
}

#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o755))
        .with_context(|| format!("failed to make {} executable", path.display()))
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> Result<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sync::{
        SYNC_BASE_URL_ENV_VAR, SYNC_ORGANIZATION_ID_ENV_VAR, SYNC_TOKEN_ENV_VAR, SavedSyncConfig,
        save_sync_config,
    };
    use crate::sync_schedule::{
        ScheduleBackend, ScheduleBackendKind, ScheduleDefinition, ScheduleState,
        expected_definition_with_exe,
    };
    use crate::test_support::{ScopedEnvVar, lock_env};
    use anyhow::Result;
    use std::fs;
    use std::process::Command;
    use tempfile::tempdir;

    fn init_repo(path: &std::path::Path) -> Result<()> {
        fs::create_dir_all(path)?;
        let status = Command::new("git").current_dir(path).arg("init").status()?;
        assert!(status.success());
        Ok(())
    }

    fn unset_sync_env() -> [ScopedEnvVar; 3] {
        [
            ScopedEnvVar::unset(SYNC_BASE_URL_ENV_VAR),
            ScopedEnvVar::unset(SYNC_ORGANIZATION_ID_ENV_VAR),
            ScopedEnvVar::unset(SYNC_TOKEN_ENV_VAR),
        ]
    }

    #[derive(Debug)]
    struct FakeScheduleBackend {
        state: ScheduleState,
        installs: usize,
    }

    impl FakeScheduleBackend {
        fn new(state: ScheduleState) -> Self {
            Self { state, installs: 0 }
        }
    }

    impl ScheduleBackend for FakeScheduleBackend {
        fn kind(&self) -> ScheduleBackendKind {
            ScheduleBackendKind::LinuxSystemd
        }

        fn state(&self) -> Result<ScheduleState> {
            Ok(self.state.clone())
        }

        fn install(&mut self, expected: &ScheduleDefinition) -> Result<()> {
            self.state = ScheduleState::Installed(expected.clone());
            self.installs += 1;
            Ok(())
        }

        fn uninstall(&mut self) -> Result<()> {
            self.state = ScheduleState::Missing;
            Ok(())
        }
    }

    fn save_valid_sync_config() -> Result<()> {
        save_sync_config(&SavedSyncConfig {
            base_url: "https://api.example.com".to_string(),
            organization_id: "org-1".to_string(),
            organization_name: Some("Example".to_string()),
            member_email: Some("dev@example.com".to_string()),
            token: "token-1".to_string(),
        })?;
        Ok(())
    }

    #[test]
    fn install_creates_managed_pre_commit_hook() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        let hook = repo.join(".git/hooks/pre-commit");
        let contents = fs::read_to_string(&hook)?;
        assert!(contents.contains(PACEFLOW_HOOK_MARKER));
        assert!(contents.contains(PACEFLOW_HOOK_KIND_COMPOSITE));
        assert!(contents.contains("paceflow hooks pre-commit --repo \"$root\" || exit $?"));
        assert!(contents.contains("pre-commit run --hook-stage pre-commit"));
        assert!(!contents.contains("exec paceflow hooks pre-commit"));
        assert!(!contents.contains("\r\n"));
        Ok(())
    }

    #[test]
    fn hook_contents_interpolates_marker_once() {
        let contents = hook_contents();
        assert!(contents.contains(&format!("# {PACEFLOW_HOOK_MARKER}")));
        assert!(contents.contains(&format!("# {PACEFLOW_HOOK_KIND_COMPOSITE}")));
    }

    #[test]
    fn install_chains_existing_foreign_hook() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        let original = "#!/bin/sh\necho existing\n";
        fs::write(&hook, original)?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        // Active hook is now the composite.
        let active = fs::read_to_string(&hook)?;
        assert!(is_paceflow_managed(&active));
        assert_eq!(classify_hook(Some(&active)), HookKind::PaceflowComposite);

        // The original was preserved as a chained backup.
        let backup = chained_hook_path(&hook);
        assert_eq!(fs::read_to_string(&backup)?, original);
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn install_chains_foreign_hook_preserves_exec_bit() -> Result<()> {
        use std::os::unix::fs::PermissionsExt;
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        fs::write(&hook, "#!/bin/sh\necho existing\n")?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        let backup = chained_hook_path(&hook);
        let mode = fs::metadata(&backup)?.permissions().mode();
        assert_ne!(mode & 0o111, 0, "backup should be executable");
        Ok(())
    }

    #[test]
    fn install_force_overwrites_foreign_hook() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        fs::write(&hook, "#!/bin/sh\necho existing\n")?;

        install_hook(Some(repo.to_string_lossy().as_ref()), true)?;

        let active = fs::read_to_string(&hook)?;
        assert_eq!(classify_hook(Some(&active)), HookKind::PaceflowComposite);
        assert!(!chained_hook_path(&hook).exists());
        Ok(())
    }

    #[test]
    fn install_chains_precommit_framework_hook() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        let framework =
            "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n";
        fs::write(&hook, framework)?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        let active = fs::read_to_string(&hook)?;
        assert_eq!(classify_hook(Some(&active)), HookKind::PaceflowComposite);
        assert_eq!(fs::read_to_string(chained_hook_path(&hook))?, framework);
        Ok(())
    }

    #[test]
    fn install_does_not_clobber_existing_chained_backup() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        fs::write(&hook, "#!/bin/sh\necho foreign\n")?;
        let backup = chained_hook_path(&hook);
        fs::write(&backup, "#!/bin/sh\necho saved-original\n")?;

        let err = install_hook(Some(repo.to_string_lossy().as_ref()), false)
            .expect_err("should refuse to clobber backup");
        assert!(
            err.to_string()
                .contains("chained hook backup already exists")
        );
        // Saved backup is untouched.
        assert_eq!(
            fs::read_to_string(&backup)?,
            "#!/bin/sh\necho saved-original\n"
        );
        Ok(())
    }

    #[test]
    fn install_repairs_windows_migrated_state() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        // pre-commit's wrapper now owns pre-commit; our hook was moved aside to pre-commit.legacy.
        fs::write(
            &hook,
            "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n",
        )?;
        let legacy = legacy_hook_path(&hook);
        fs::write(
            &legacy,
            format!("#!/bin/sh\n# {PACEFLOW_HOOK_MARKER}\nexit 0\n"),
        )?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        let active = fs::read_to_string(&hook)?;
        assert_eq!(classify_hook(Some(&active)), HookKind::PaceflowComposite);
        assert!(!legacy.exists(), "legacy hook should be removed");
        Ok(())
    }

    #[test]
    fn install_updates_existing_paceflow_hook() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        // Legacy plain shim (marker present, no composite sentinel).
        fs::write(
            &hook,
            format!(
                "#!/bin/sh\n# {PACEFLOW_HOOK_MARKER}\nexec paceflow hooks pre-commit --repo \"$root\"\nold\n"
            ),
        )?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;

        let contents = fs::read_to_string(&hook)?;
        assert_eq!(classify_hook(Some(&contents)), HookKind::PaceflowComposite);
        assert!(!contents.contains("old"));
        assert!(!contents.contains("exec paceflow hooks pre-commit"));
        Ok(())
    }

    #[test]
    fn uninstall_restores_chained_backup() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");
        let original = "#!/bin/sh\necho existing\n";
        fs::write(&hook, original)?;

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;
        uninstall_hook(Some(repo.to_string_lossy().as_ref()))?;

        assert_eq!(fs::read_to_string(&hook)?, original);
        assert!(!chained_hook_path(&hook).exists());
        Ok(())
    }

    #[test]
    fn uninstall_removes_hook_without_backup() -> Result<()> {
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let hook = repo.join(".git/hooks/pre-commit");

        install_hook(Some(repo.to_string_lossy().as_ref()), false)?;
        uninstall_hook(Some(repo.to_string_lossy().as_ref()))?;

        assert!(!hook.exists());
        Ok(())
    }

    #[test]
    fn classify_hook_recognizes_each_kind() {
        assert_eq!(classify_hook(None), HookKind::None);
        assert_eq!(
            classify_hook(Some(&hook_contents())),
            HookKind::PaceflowComposite
        );
        assert_eq!(
            classify_hook(Some(&format!("# {PACEFLOW_HOOK_MARKER}\nexec paceflow\n"))),
            HookKind::PaceflowPlain
        );
        assert_eq!(
            classify_hook(Some("# File generated by pre-commit\n")),
            HookKind::PrecommitFramework
        );
        assert_eq!(
            classify_hook(Some("#!/bin/sh\necho hi\n")),
            HookKind::OtherForeign
        );
    }

    #[test]
    fn pre_commit_check_fails_without_sync_config() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _sync_env = unset_sync_env();

        let err = check_sync_configured().expect_err("should require sync config");

        assert!(err.to_string().contains("paceflow sync is not configured"));
        Ok(())
    }

    #[test]
    fn pre_commit_check_accepts_saved_sync_config() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _sync_env = unset_sync_env();
        save_sync_config(&SavedSyncConfig {
            base_url: "https://api.example.com".to_string(),
            organization_id: "org-1".to_string(),
            organization_name: Some("Example".to_string()),
            member_email: Some("dev@example.com".to_string()),
            token: "token-1".to_string(),
        })?;

        check_sync_configured()?;
        Ok(())
    }

    #[test]
    fn pre_commit_check_accepts_env_only_sync_config() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _base = ScopedEnvVar::set(SYNC_BASE_URL_ENV_VAR, "https://api.example.com");
        let _org = ScopedEnvVar::set(SYNC_ORGANIZATION_ID_ENV_VAR, "org-1");
        let _token = ScopedEnvVar::set(SYNC_TOKEN_ENV_VAR, "token-1");

        check_sync_configured()?;
        Ok(())
    }

    #[test]
    fn pre_commit_check_uses_saved_over_env_when_both_present() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _base = ScopedEnvVar::set(SYNC_BASE_URL_ENV_VAR, "https://env.example.com");
        let _org = ScopedEnvVar::set(SYNC_ORGANIZATION_ID_ENV_VAR, "env-org");
        let _token = ScopedEnvVar::set(SYNC_TOKEN_ENV_VAR, "env-token");
        save_sync_config(&SavedSyncConfig {
            base_url: "https://saved.example.com".to_string(),
            organization_id: "saved-org".to_string(),
            organization_name: Some("Saved".to_string()),
            member_email: Some("saved@example.com".to_string()),
            token: "saved-token".to_string(),
        })?;

        check_sync_configured()?;
        Ok(())
    }

    #[test]
    fn pre_commit_check_surfaces_malformed_saved_base_url_even_when_env_is_valid() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _base = ScopedEnvVar::set(SYNC_BASE_URL_ENV_VAR, "https://env.example.com");
        let _org = ScopedEnvVar::set(SYNC_ORGANIZATION_ID_ENV_VAR, "env-org");
        let _token = ScopedEnvVar::set(SYNC_TOKEN_ENV_VAR, "env-token");
        save_sync_config(&SavedSyncConfig {
            base_url: "not-a-url".to_string(),
            organization_id: "saved-org".to_string(),
            organization_name: Some("Saved".to_string()),
            member_email: Some("saved@example.com".to_string()),
            token: "saved-token".to_string(),
        })?;

        let err = check_sync_configured().expect_err("malformed saved base URL should win");
        assert!(err.to_string().contains("sync base URL must start"));
        Ok(())
    }

    #[test]
    fn pre_commit_check_reports_malformed_base_url() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _base = ScopedEnvVar::set(SYNC_BASE_URL_ENV_VAR, "api.example.com");
        let _org = ScopedEnvVar::set(SYNC_ORGANIZATION_ID_ENV_VAR, "org-1");
        let _token = ScopedEnvVar::set(SYNC_TOKEN_ENV_VAR, "token-1");

        let err = check_sync_configured().expect_err("should reject malformed base URL");

        assert!(err.to_string().contains("sync base URL must start"));
        Ok(())
    }

    #[test]
    fn pre_commit_installs_missing_schedule_after_sync_config_check() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _sync_env = unset_sync_env();
        save_valid_sync_config()?;
        let mut backend = FakeScheduleBackend::new(ScheduleState::Missing);

        run_pre_commit_with_backend(
            HooksRepoArgs {
                repo: Some(repo.to_string_lossy().to_string()),
            },
            &mut backend,
        )?;

        assert_eq!(backend.installs, 1);
        assert_eq!(
            backend.state,
            ScheduleState::Installed(expected_definition_with_exe(
                ScheduleBackendKind::LinuxSystemd,
                std::env::current_exe()?
            ))
        );
        Ok(())
    }

    #[test]
    fn pre_commit_passes_when_schedule_is_already_installed() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _sync_env = unset_sync_env();
        save_valid_sync_config()?;
        let mut backend =
            FakeScheduleBackend::new(ScheduleState::Installed(expected_definition_with_exe(
                ScheduleBackendKind::LinuxSystemd,
                std::env::current_exe()?,
            )));

        run_pre_commit_with_backend(
            HooksRepoArgs {
                repo: Some(repo.to_string_lossy().to_string()),
            },
            &mut backend,
        )?;

        assert_eq!(backend.installs, 0);
        Ok(())
    }

    #[test]
    fn pre_commit_missing_sync_blocks_before_schedule_install() -> Result<()> {
        let _guard = lock_env();
        let tempdir = tempdir()?;
        let repo = tempdir.path().join("repo");
        init_repo(&repo)?;
        let _home = ScopedEnvVar::set("PACEFLOW_HOME", tempdir.path());
        let _sync_env = unset_sync_env();
        let mut backend = FakeScheduleBackend::new(ScheduleState::Missing);

        let err = run_pre_commit_with_backend(
            HooksRepoArgs {
                repo: Some(repo.to_string_lossy().to_string()),
            },
            &mut backend,
        )
        .expect_err("missing sync should block");

        assert!(err.to_string().contains("paceflow sync is not configured"));
        assert_eq!(backend.installs, 0);
        Ok(())
    }
}
